[project]
name = "sconce"
version = "0.0.40"
description = "sconce: torch helper"
authors = [{ name = "Sathyaprakash Narayanan", email = "snaray17@ucsc.edu" }]
urls = { code = "https://github.com/satabios/sconce" }

dynamic = ["dependencies" ,"readme"]
[tool.setuptools.dynamic]

dependencies = {file = ["requirements.txt"]}