[build-system]
requires = ["flit_core >=3.2,<4"]


[project]
name = "sconce"
version = "0.61"
description = "sconce: torch pipeliner"
authors = [{ name = "Sathyaprakash Narayanan", email = "snaray17@ucsc.edu" }]
urls = { code = "https://github.com/satabios/sconce" }

dynamic = ["dependencies" ,"readme","requires-python","classifiers","keywords", "license"]
